version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - app-networks

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    environment:
      - mongo_url=mongodb+srv://shmp:shmp@cluster27.d6hauw2.mongodb.net/shmp?retryWrites=true&w=majority
      - jwt_secret=shmp
      - cloud_name=dejm9izfx
      - cloud_api_key=555179651852497
      - cloud_api_secret=BueLBWwGGQkuf6BjLM2n8v4pJRM
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge
